### ISSUE TITLE
Error: Message Failed

### ISSUE THREAD

**Issue by sylv256** [sentanos/roblox-js-server#71] opened 2018-02-19 02:08 UTC
Whenever I use the message function, the application will say:
```
Unhandled rejection Error: Message failed
    at /Users/laurenturner/Documents/TehcBot/node_modules/roblox-js/lib/user/message.js:37:13
    at tryCatcher (/Users/laurenturner/Documents/TehcBot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/laurenturner/Documents/TehcBot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/laurenturner/Documents/TehcBot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/laurenturner/Documents/TehcBot/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/laurenturner/Documents/TehcBot/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/laurenturner/Documents/TehcBot/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/laurenturner/Documents/TehcBot/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/laurenturner/Documents/TehcBot/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

Does anyone have any idea why this is happening?

Code:
```js
var roblox = require("roblox-js");

var Bot = {
	username: "I put my username here",
	password: "I put my password here"
};

function login () {
	return roblox.login(Bot.username, Bot.password);
};

login().then(function() {
	console.log('Client: Logged In');
	roblox.message({recipient: 386470081, subject: "testing", body: "testin"})
});
```

**Comment by sylv256** [comment] 2018-02-19 02:12
I found the HTTP status was 403 Forbidden. Does anyone know why?

**Comment by sentanos** [comment] 2018-02-19 09:29
This is in the wrong repository and is also a duplicate of many other issues: https://github.com/sentanos/roblox-js/issues?utf8=✓&q=Message+failed

**Closed as completed by sentanos** 2018-02-19 09:29 UTC
