### ISSUE TITLE
Command prompt error

### ISSUE THREAD

**Issue by deathxrose** [sentanos/roblox-js-server#41] opened 2017-07-10 19:40 UTC
I'm typing heroku login username password and it says heroku is not a command?

**Comment by deathxrose** [comment] 2017-07-10 19:42
This is what happens if i try to open server 
![snipsls](https://user-images.githubusercontent.com/19968356/28036484-a3e7c1c6-6575-11e7-9b43-d59e8cfe7cc6.PNG)

**Comment by slossgaming** [comment] 2017-07-11 02:17
You have to run it in command prompt, Do that by pressing ctrl+R, then cd to the dir, then put in node server.js

You can't click to run it.

**Comment by slossgaming** [comment] 2017-07-11 02:17
You also have to download the programs from both websites, Download Node.JS, and Heroku command line thingy

**Comment by sentanos** [comment] 2017-07-13 06:58
Duplicate of #40

**Closed** 2017-07-13 06:58 UTC
