### ISSUE TITLE
Message Failed: Captcha

### ISSUE THREAD

**Issue by conman0552** [sentanos/roblox-js-server#35] opened 2017-06-13 21:30 UTC
I have been getting this error whenever I try to use anything pertaining to the bot.  

![image](https://user-images.githubusercontent.com/24281023/27105536-8cdd2500-5055-11e7-904b-e1792eaa06ae.png)

**Comment by sentanos** [comment] 2017-06-13 22:50
Duplicate of #31

**Closed by sentanos** 2017-06-13 22:50 UTC
