### ISSUE TITLE
Payout [Request]

### ISSUE THREAD

**Issue by teddymisty132** [sentanos/roblox-js-server#65] opened 2018-01-05 01:00 UTC
I feel this would be an amazing feature for groups that pay workers, R$ Rewards, or even a refund feature.

**Comment by teddymisty132** [comment] 2018-01-05 01:17
I also don't really have any experience with JS besides Discord Bots.

**Comment by sentanos** [comment] 2018-01-05 01:21
Duplicate of #50

**Closed as completed by sentanos** 2018-01-05 01:21 UTC
